package com.cbtuser.entity;
// Generated Nov 6, 2019 10:33:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
@Entity
@Table(name="administrator"
    ,catalog="computerbasedtest"
)
public class Administrator  implements java.io.Serializable {


     private String id;
     private String username;
     private String password;
     private String name;
     private String phoneNumber;
     private String email;
     private Set<Adminlog> adminlogs = new HashSet<Adminlog>(0);
     private Set<Test> tests = new HashSet<Test>(0);

    public Administrator() {
    }

	
    public Administrator(String id, String username, String password, String name) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.name = name;
    }
    public Administrator(String id, String username, String password, String name, String phoneNumber, String email, Set<Adminlog> adminlogs, Set<Test> tests) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.adminlogs = adminlogs;
       this.tests = tests;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=5)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=24)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=24)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone_number", length=13)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="email", length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="administrator")
    public Set<Adminlog> getAdminlogs() {
        return this.adminlogs;
    }
    
    public void setAdminlogs(Set<Adminlog> adminlogs) {
        this.adminlogs = adminlogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="administrator")
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }




}


