package com.cbtuser.entity;
// Generated Nov 11, 2019 11:56:01 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adminlog generated by hbm2java
 */
@Entity
@Table(name="adminlog"
    ,catalog="computerbasedtest"
)
public class Adminlog  implements java.io.Serializable {


     private String id;
     private Administrator administrator;
     private String logname;

    public Adminlog() {
    }

    public Adminlog(String id, Administrator administrator, String logname) {
       this.id = id;
       this.administrator = administrator;
       this.logname = logname;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=15)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Administrator_id", nullable=false)
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }

    
    @Column(name="logname", nullable=false, length=100)
    public String getLogname() {
        return this.logname;
    }
    
    public void setLogname(String logname) {
        this.logname = logname;
    }




}


