package com.cbtuser.entity;
// Generated Oct 19, 2019 10:48:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AudansquestionId generated by hbm2java
 */
@Embeddable
public class AudansquestionId  implements java.io.Serializable {


     private int id;
     private int audioQuestionId;
     private String audioQuestionQuestionDbId;
     private String audioQuestionSubTestId;

    public AudansquestionId() {
    }

    public AudansquestionId(int id, int audioQuestionId, String audioQuestionQuestionDbId, String audioQuestionSubTestId) {
       this.id = id;
       this.audioQuestionId = audioQuestionId;
       this.audioQuestionQuestionDbId = audioQuestionQuestionDbId;
       this.audioQuestionSubTestId = audioQuestionSubTestId;
    }
   


    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="AudioQuestion_id", nullable=false)
    public int getAudioQuestionId() {
        return this.audioQuestionId;
    }
    
    public void setAudioQuestionId(int audioQuestionId) {
        this.audioQuestionId = audioQuestionId;
    }


    @Column(name="AudioQuestion_QuestionDB_id", nullable=false, length=10)
    public String getAudioQuestionQuestionDbId() {
        return this.audioQuestionQuestionDbId;
    }
    
    public void setAudioQuestionQuestionDbId(String audioQuestionQuestionDbId) {
        this.audioQuestionQuestionDbId = audioQuestionQuestionDbId;
    }


    @Column(name="AudioQuestion_SubTest_id", nullable=false, length=10)
    public String getAudioQuestionSubTestId() {
        return this.audioQuestionSubTestId;
    }
    
    public void setAudioQuestionSubTestId(String audioQuestionSubTestId) {
        this.audioQuestionSubTestId = audioQuestionSubTestId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AudansquestionId) ) return false;
		 AudansquestionId castOther = ( AudansquestionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getAudioQuestionId()==castOther.getAudioQuestionId())
 && ( (this.getAudioQuestionQuestionDbId()==castOther.getAudioQuestionQuestionDbId()) || ( this.getAudioQuestionQuestionDbId()!=null && castOther.getAudioQuestionQuestionDbId()!=null && this.getAudioQuestionQuestionDbId().equals(castOther.getAudioQuestionQuestionDbId()) ) )
 && ( (this.getAudioQuestionSubTestId()==castOther.getAudioQuestionSubTestId()) || ( this.getAudioQuestionSubTestId()!=null && castOther.getAudioQuestionSubTestId()!=null && this.getAudioQuestionSubTestId().equals(castOther.getAudioQuestionSubTestId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getAudioQuestionId();
         result = 37 * result + ( getAudioQuestionQuestionDbId() == null ? 0 : this.getAudioQuestionQuestionDbId().hashCode() );
         result = 37 * result + ( getAudioQuestionSubTestId() == null ? 0 : this.getAudioQuestionSubTestId().hashCode() );
         return result;
   }   


}


