package com.cbtuser.entity;
// Generated Nov 6, 2019 10:33:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AudansquestionId generated by hbm2java
 */
@Embeddable
public class AudansquestionId  implements java.io.Serializable {


     private int id;
     private String audioQuestionId;
     private String audioQuestionSubTestDatabaseId;

    public AudansquestionId() {
    }

    public AudansquestionId(int id, String audioQuestionId, String audioQuestionSubTestDatabaseId) {
       this.id = id;
       this.audioQuestionId = audioQuestionId;
       this.audioQuestionSubTestDatabaseId = audioQuestionSubTestDatabaseId;
    }
   


    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="AudioQuestion_id", nullable=false, length=10)
    public String getAudioQuestionId() {
        return this.audioQuestionId;
    }
    
    public void setAudioQuestionId(String audioQuestionId) {
        this.audioQuestionId = audioQuestionId;
    }


    @Column(name="AudioQuestion_SubTestDatabase_id", nullable=false, length=10)
    public String getAudioQuestionSubTestDatabaseId() {
        return this.audioQuestionSubTestDatabaseId;
    }
    
    public void setAudioQuestionSubTestDatabaseId(String audioQuestionSubTestDatabaseId) {
        this.audioQuestionSubTestDatabaseId = audioQuestionSubTestDatabaseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AudansquestionId) ) return false;
		 AudansquestionId castOther = ( AudansquestionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getAudioQuestionId()==castOther.getAudioQuestionId()) || ( this.getAudioQuestionId()!=null && castOther.getAudioQuestionId()!=null && this.getAudioQuestionId().equals(castOther.getAudioQuestionId()) ) )
 && ( (this.getAudioQuestionSubTestDatabaseId()==castOther.getAudioQuestionSubTestDatabaseId()) || ( this.getAudioQuestionSubTestDatabaseId()!=null && castOther.getAudioQuestionSubTestDatabaseId()!=null && this.getAudioQuestionSubTestDatabaseId().equals(castOther.getAudioQuestionSubTestDatabaseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getAudioQuestionId() == null ? 0 : this.getAudioQuestionId().hashCode() );
         result = 37 * result + ( getAudioQuestionSubTestDatabaseId() == null ? 0 : this.getAudioQuestionSubTestDatabaseId().hashCode() );
         return result;
   }   


}


