package com.cbtuser.entity;
// Generated Nov 25, 2019 1:19:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursedatabase generated by hbm2java
 */
@Entity
@Table(name="coursedatabase"
    ,catalog="computerbasedtest"
)
public class Coursedatabase  implements java.io.Serializable {


     private String id;
     private User user;
     private String name;
     private Set<Question> questions = new HashSet<Question>(0);
     private Set<Subtest> subtests = new HashSet<Subtest>(0);

    public Coursedatabase() {
    }

	
    public Coursedatabase(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Coursedatabase(String id, User user, String name, Set<Question> questions, Set<Subtest> subtests) {
       this.id = id;
       this.user = user;
       this.name = name;
       this.questions = questions;
       this.subtests = subtests;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=9)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coursedatabase")
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coursedatabase")
    public Set<Subtest> getSubtests() {
        return this.subtests;
    }
    
    public void setSubtests(Set<Subtest> subtests) {
        this.subtests = subtests;
    }




}


