package com.cbtuser.entity;
// Generated Nov 8, 2019 8:58:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImgansquestionId generated by hbm2java
 */
@Embeddable
public class ImgansquestionId  implements java.io.Serializable {


     private int id;
     private String imageQuestionId;
     private String imageQuestionSubTestDatabaseId;

    public ImgansquestionId() {
    }

    public ImgansquestionId(int id, String imageQuestionId, String imageQuestionSubTestDatabaseId) {
       this.id = id;
       this.imageQuestionId = imageQuestionId;
       this.imageQuestionSubTestDatabaseId = imageQuestionSubTestDatabaseId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="ImageQuestion_id", nullable=false, length=10)
    public String getImageQuestionId() {
        return this.imageQuestionId;
    }
    
    public void setImageQuestionId(String imageQuestionId) {
        this.imageQuestionId = imageQuestionId;
    }


    @Column(name="ImageQuestion_SubTestDatabase_id", nullable=false, length=8)
    public String getImageQuestionSubTestDatabaseId() {
        return this.imageQuestionSubTestDatabaseId;
    }
    
    public void setImageQuestionSubTestDatabaseId(String imageQuestionSubTestDatabaseId) {
        this.imageQuestionSubTestDatabaseId = imageQuestionSubTestDatabaseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImgansquestionId) ) return false;
		 ImgansquestionId castOther = ( ImgansquestionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getImageQuestionId()==castOther.getImageQuestionId()) || ( this.getImageQuestionId()!=null && castOther.getImageQuestionId()!=null && this.getImageQuestionId().equals(castOther.getImageQuestionId()) ) )
 && ( (this.getImageQuestionSubTestDatabaseId()==castOther.getImageQuestionSubTestDatabaseId()) || ( this.getImageQuestionSubTestDatabaseId()!=null && castOther.getImageQuestionSubTestDatabaseId()!=null && this.getImageQuestionSubTestDatabaseId().equals(castOther.getImageQuestionSubTestDatabaseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getImageQuestionId() == null ? 0 : this.getImageQuestionId().hashCode() );
         result = 37 * result + ( getImageQuestionSubTestDatabaseId() == null ? 0 : this.getImageQuestionSubTestDatabaseId().hashCode() );
         return result;
   }   


}


