package com.cbtuser.entity;
// Generated Nov 15, 2019 8:43:31 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MediacontentId generated by hbm2java
 */
@Embeddable
public class MediacontentId  implements java.io.Serializable {


     private String questionId;
     private String questionSubTestDatabaseId;
     private int mediaId;

    public MediacontentId() {
    }

    public MediacontentId(String questionId, String questionSubTestDatabaseId, int mediaId) {
       this.questionId = questionId;
       this.questionSubTestDatabaseId = questionSubTestDatabaseId;
       this.mediaId = mediaId;
    }
   


    @Column(name="Question_id", nullable=false, length=12)
    public String getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }


    @Column(name="Question_SubTestDatabase_id", nullable=false, length=8)
    public String getQuestionSubTestDatabaseId() {
        return this.questionSubTestDatabaseId;
    }
    
    public void setQuestionSubTestDatabaseId(String questionSubTestDatabaseId) {
        this.questionSubTestDatabaseId = questionSubTestDatabaseId;
    }


    @Column(name="Media_id", nullable=false)
    public int getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(int mediaId) {
        this.mediaId = mediaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MediacontentId) ) return false;
		 MediacontentId castOther = ( MediacontentId ) other; 
         
		 return ( (this.getQuestionId()==castOther.getQuestionId()) || ( this.getQuestionId()!=null && castOther.getQuestionId()!=null && this.getQuestionId().equals(castOther.getQuestionId()) ) )
 && ( (this.getQuestionSubTestDatabaseId()==castOther.getQuestionSubTestDatabaseId()) || ( this.getQuestionSubTestDatabaseId()!=null && castOther.getQuestionSubTestDatabaseId()!=null && this.getQuestionSubTestDatabaseId().equals(castOther.getQuestionSubTestDatabaseId()) ) )
 && (this.getMediaId()==castOther.getMediaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getQuestionId() == null ? 0 : this.getQuestionId().hashCode() );
         result = 37 * result + ( getQuestionSubTestDatabaseId() == null ? 0 : this.getQuestionSubTestDatabaseId().hashCode() );
         result = 37 * result + this.getMediaId();
         return result;
   }   


}


