package com.cbtuser.entity;
// Generated Nov 15, 2019 8:43:31 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mediacontent generated by hbm2java
 */
@Entity
@Table(name="mediacontent"
    ,catalog="computerbasedtest"
)
public class Mediacontent  implements java.io.Serializable {


     private MediacontentId id;
     private Media media;
     private Question question;
     private String mediaAddress;

    public Mediacontent() {
    }

    public Mediacontent(MediacontentId id, Media media, Question question, String mediaAddress) {
       this.id = id;
       this.media = media;
       this.question = question;
       this.mediaAddress = mediaAddress;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="questionId", column=@Column(name="Question_id", nullable=false, length=12) ), 
        @AttributeOverride(name="questionSubTestDatabaseId", column=@Column(name="Question_SubTestDatabase_id", nullable=false, length=8) ), 
        @AttributeOverride(name="mediaId", column=@Column(name="Media_id", nullable=false) ) } )
    public MediacontentId getId() {
        return this.id;
    }
    
    public void setId(MediacontentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Media_id", nullable=false, insertable=false, updatable=false)
    public Media getMedia() {
        return this.media;
    }
    
    public void setMedia(Media media) {
        this.media = media;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Question_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Question_SubTestDatabase_id", referencedColumnName="SubTestDatabase_id", nullable=false, insertable=false, updatable=false) } )
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }

    
    @Column(name="media_address", nullable=false, length=200)
    public String getMediaAddress() {
        return this.mediaAddress;
    }
    
    public void setMediaAddress(String mediaAddress) {
        this.mediaAddress = mediaAddress;
    }




}


