package com.cbtuser.entity;
// Generated Nov 6, 2019 10:33:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Normalquestion generated by hbm2java
 */
@Entity
@Table(name="normalquestion"
    ,catalog="computerbasedtest"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class Normalquestion  implements java.io.Serializable {


     private NormalquestionId id;
     private Subtestdatabase subtestdatabase;
     private String content;
     private Set<Nrmansquestion> nrmansquestions = new HashSet<Nrmansquestion>(0);

    public Normalquestion() {
    }

	
    public Normalquestion(NormalquestionId id, Subtestdatabase subtestdatabase, String content) {
        this.id = id;
        this.subtestdatabase = subtestdatabase;
        this.content = content;
    }
    public Normalquestion(NormalquestionId id, Subtestdatabase subtestdatabase, String content, Set<Nrmansquestion> nrmansquestions) {
       this.id = id;
       this.subtestdatabase = subtestdatabase;
       this.content = content;
       this.nrmansquestions = nrmansquestions;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", unique=true, nullable=false, length=10) ), 
        @AttributeOverride(name="subTestDatabaseId", column=@Column(name="SubTestDatabase_id", nullable=false, length=8) ) } )
    public NormalquestionId getId() {
        return this.id;
    }
    
    public void setId(NormalquestionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubTestDatabase_id", nullable=false, insertable=false, updatable=false)
    public Subtestdatabase getSubtestdatabase() {
        return this.subtestdatabase;
    }
    
    public void setSubtestdatabase(Subtestdatabase subtestdatabase) {
        this.subtestdatabase = subtestdatabase;
    }

    
    @Column(name="content", nullable=false, length=1000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="normalquestion")
    public Set<Nrmansquestion> getNrmansquestions() {
        return this.nrmansquestions;
    }
    
    public void setNrmansquestions(Set<Nrmansquestion> nrmansquestions) {
        this.nrmansquestions = nrmansquestions;
    }




}


