package com.cbtuser.entity;
// Generated Nov 8, 2019 8:58:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NrmansquestionId generated by hbm2java
 */
@Embeddable
public class NrmansquestionId  implements java.io.Serializable {


     private int id;
     private String normalQuestionId;
     private String normalQuestionSubTestDatabaseId;

    public NrmansquestionId() {
    }

    public NrmansquestionId(int id, String normalQuestionId, String normalQuestionSubTestDatabaseId) {
       this.id = id;
       this.normalQuestionId = normalQuestionId;
       this.normalQuestionSubTestDatabaseId = normalQuestionSubTestDatabaseId;
    }
   


    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="NormalQuestion_id", nullable=false, length=10)
    public String getNormalQuestionId() {
        return this.normalQuestionId;
    }
    
    public void setNormalQuestionId(String normalQuestionId) {
        this.normalQuestionId = normalQuestionId;
    }


    @Column(name="NormalQuestion_SubTestDatabase_id", nullable=false, length=8)
    public String getNormalQuestionSubTestDatabaseId() {
        return this.normalQuestionSubTestDatabaseId;
    }
    
    public void setNormalQuestionSubTestDatabaseId(String normalQuestionSubTestDatabaseId) {
        this.normalQuestionSubTestDatabaseId = normalQuestionSubTestDatabaseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NrmansquestionId) ) return false;
		 NrmansquestionId castOther = ( NrmansquestionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getNormalQuestionId()==castOther.getNormalQuestionId()) || ( this.getNormalQuestionId()!=null && castOther.getNormalQuestionId()!=null && this.getNormalQuestionId().equals(castOther.getNormalQuestionId()) ) )
 && ( (this.getNormalQuestionSubTestDatabaseId()==castOther.getNormalQuestionSubTestDatabaseId()) || ( this.getNormalQuestionSubTestDatabaseId()!=null && castOther.getNormalQuestionSubTestDatabaseId()!=null && this.getNormalQuestionSubTestDatabaseId().equals(castOther.getNormalQuestionSubTestDatabaseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getNormalQuestionId() == null ? 0 : this.getNormalQuestionId().hashCode() );
         result = 37 * result + ( getNormalQuestionSubTestDatabaseId() == null ? 0 : this.getNormalQuestionSubTestDatabaseId().hashCode() );
         return result;
   }   


}


