package com.cbtuser.entity;
// Generated Oct 18, 2019 8:58:09 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Nrmansquestion generated by hbm2java
 */
@Entity
@Table(name="nrmansquestion"
    ,catalog="computerbasedtest"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class Nrmansquestion  implements java.io.Serializable {


     private NrmansquestionId id;
     private Normalquestion normalquestion;
     private String content;

    public Nrmansquestion() {
    }

    public Nrmansquestion(NrmansquestionId id, Normalquestion normalquestion, String content) {
       this.id = id;
       this.normalquestion = normalquestion;
       this.content = content;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", unique=true, nullable=false) ), 
        @AttributeOverride(name="normalQuestionId", column=@Column(name="NormalQuestion_id", nullable=false) ), 
        @AttributeOverride(name="normalQuestionQuestionDbId", column=@Column(name="NormalQuestion_QuestionDB_id", nullable=false, length=10) ), 
        @AttributeOverride(name="normalQuestionSubTestId", column=@Column(name="NormalQuestion_SubTest_id", nullable=false, length=10) ) } )
    public NrmansquestionId getId() {
        return this.id;
    }
    
    public void setId(NrmansquestionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="NormalQuestion_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="NormalQuestion_QuestionDB_id", referencedColumnName="QuestionDB_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="NormalQuestion_SubTest_id", referencedColumnName="SubTest_id", nullable=false, insertable=false, updatable=false) } )
    public Normalquestion getNormalquestion() {
        return this.normalquestion;
    }
    
    public void setNormalquestion(Normalquestion normalquestion) {
        this.normalquestion = normalquestion;
    }

    
    @Column(name="content", nullable=false, length=500)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


