package com.cbtuser.entity;
// Generated Oct 18, 2019 8:58:09 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Questionmakerlog generated by hbm2java
 */
@Entity
@Table(name="questionmakerlog"
    ,catalog="computerbasedtest"
)
public class Questionmakerlog  implements java.io.Serializable {


     private String id;
     private Questionmaker questionmaker;
     private String name;
     private String logname;

    public Questionmakerlog() {
    }

    public Questionmakerlog(String id, Questionmaker questionmaker, String name, String logname) {
       this.id = id;
       this.questionmaker = questionmaker;
       this.name = name;
       this.logname = logname;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=15)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QuestionMaker_id", nullable=false)
    public Questionmaker getQuestionmaker() {
        return this.questionmaker;
    }
    
    public void setQuestionmaker(Questionmaker questionmaker) {
        this.questionmaker = questionmaker;
    }

    
    @Column(name="name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="logname", nullable=false, length=100)
    public String getLogname() {
        return this.logname;
    }
    
    public void setLogname(String logname) {
        this.logname = logname;
    }




}


