package com.cbtuser.entity;
// Generated Oct 19, 2019 10:48:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Questionmaker generated by hbm2java
 */
@Entity
@Table(name="questionmaker"
    ,catalog="computerbasedtest"
)
public class Questionmaker  implements java.io.Serializable {


     private String id;
     private String username;
     private String password;
     private String name;
     private String phoneNumber;
     private String email;
     private Set<Test> tests = new HashSet<Test>(0);
     private Set<Questionmakerlog> questionmakerlogs = new HashSet<Questionmakerlog>(0);

    public Questionmaker() {
    }

	
    public Questionmaker(String id, String username, String password, String name) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.name = name;
    }
    public Questionmaker(String id, String username, String password, String name, String phoneNumber, String email, Set<Test> tests, Set<Questionmakerlog> questionmakerlogs) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.tests = tests;
       this.questionmakerlogs = questionmakerlogs;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=5)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=24)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=24)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone_number", length=13)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="email", length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questionmaker")
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questionmaker")
    public Set<Questionmakerlog> getQuestionmakerlogs() {
        return this.questionmakerlogs;
    }
    
    public void setQuestionmakerlogs(Set<Questionmakerlog> questionmakerlogs) {
        this.questionmakerlogs = questionmakerlogs;
    }




}


