package com.cbtuser.entity;
// Generated Nov 8, 2019 8:58:55 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Score generated by hbm2java
 */
@Entity
@Table(name="score"
    ,catalog="computerbasedtest"
)
public class Score  implements java.io.Serializable {


     private ScoreId id;
     private Participant participant;
     private Subtest subtest;
     private Double score;

    public Score() {
    }

	
    public Score(ScoreId id, Participant participant, Subtest subtest) {
        this.id = id;
        this.participant = participant;
        this.subtest = subtest;
    }
    public Score(ScoreId id, Participant participant, Subtest subtest, Double score) {
       this.id = id;
       this.participant = participant;
       this.subtest = subtest;
       this.score = score;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="participantId", column=@Column(name="Participant_id", nullable=false, length=8) ), 
        @AttributeOverride(name="subTestId", column=@Column(name="SubTest_id", nullable=false, length=8) ) } )
    public ScoreId getId() {
        return this.id;
    }
    
    public void setId(ScoreId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Participant_id", nullable=false, insertable=false, updatable=false)
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubTest_id", nullable=false, insertable=false, updatable=false)
    public Subtest getSubtest() {
        return this.subtest;
    }
    
    public void setSubtest(Subtest subtest) {
        this.subtest = subtest;
    }

    
    @Column(name="score", precision=22, scale=0)
    public Double getScore() {
        return this.score;
    }
    
    public void setScore(Double score) {
        this.score = score;
    }




}


