package com.cbtuser.entity;
// Generated Nov 24, 2019 3:56:55 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Score generated by hbm2java
 */
@Entity
@Table(name="score"
    ,catalog="computerbasedtest"
)
public class Score  implements java.io.Serializable {


     private ScoreId id;
     private Test test;
     private User user;
     private double score;

    public Score() {
    }

    public Score(ScoreId id, Test test, User user, double score) {
       this.id = id;
       this.test = test;
       this.user = user;
       this.score = score;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="testId", column=@Column(name="Test_id", nullable=false, length=9) ), 
        @AttributeOverride(name="userId", column=@Column(name="User_id", nullable=false, length=9) ) } )
    public ScoreId getId() {
        return this.id;
    }
    
    public void setId(ScoreId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Test_id", nullable=false, insertable=false, updatable=false)
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="score", nullable=false, precision=22, scale=0)
    public double getScore() {
        return this.score;
    }
    
    public void setScore(double score) {
        this.score = score;
    }




}


