package com.cbtuser.entity;
// Generated Oct 19, 2019 10:48:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subtest generated by hbm2java
 */
@Entity
@Table(name="subtest"
    ,catalog="computerbasedtest"
)
public class Subtest  implements java.io.Serializable {


     private String id;
     private Test test;
     private String token;
     private String name;
     private Date testDate;
     private int time;
     private Date dateStart;
     private Date dateFinish;
     private Set<Imagequestion> imagequestions = new HashSet<Imagequestion>(0);
     private Set<Audioquestion> audioquestions = new HashSet<Audioquestion>(0);
     private Set<Videoquestion> videoquestions = new HashSet<Videoquestion>(0);
     private Set<Normalquestion> normalquestions = new HashSet<Normalquestion>(0);
     private Set<Score> scores = new HashSet<Score>(0);

    public Subtest() {
    }

	
    public Subtest(String id, Test test, String token, String name, Date testDate, int time, Date dateStart, Date dateFinish) {
        this.id = id;
        this.test = test;
        this.token = token;
        this.name = name;
        this.testDate = testDate;
        this.time = time;
        this.dateStart = dateStart;
        this.dateFinish = dateFinish;
    }
    public Subtest(String id, Test test, String token, String name, Date testDate, int time, Date dateStart, Date dateFinish, Set<Imagequestion> imagequestions, Set<Audioquestion> audioquestions, Set<Videoquestion> videoquestions, Set<Normalquestion> normalquestions, Set<Score> scores) {
       this.id = id;
       this.test = test;
       this.token = token;
       this.name = name;
       this.testDate = testDate;
       this.time = time;
       this.dateStart = dateStart;
       this.dateFinish = dateFinish;
       this.imagequestions = imagequestions;
       this.audioquestions = audioquestions;
       this.videoquestions = videoquestions;
       this.normalquestions = normalquestions;
       this.scores = scores;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Test_id", nullable=false)
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }

    
    @Column(name="token", nullable=false, length=12)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="test_date", nullable=false, length=10)
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    
    @Column(name="time", nullable=false)
    public int getTime() {
        return this.time;
    }
    
    public void setTime(int time) {
        this.time = time;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_start", nullable=false, length=19)
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_finish", nullable=false, length=19)
    public Date getDateFinish() {
        return this.dateFinish;
    }
    
    public void setDateFinish(Date dateFinish) {
        this.dateFinish = dateFinish;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Imagequestion> getImagequestions() {
        return this.imagequestions;
    }
    
    public void setImagequestions(Set<Imagequestion> imagequestions) {
        this.imagequestions = imagequestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Audioquestion> getAudioquestions() {
        return this.audioquestions;
    }
    
    public void setAudioquestions(Set<Audioquestion> audioquestions) {
        this.audioquestions = audioquestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Videoquestion> getVideoquestions() {
        return this.videoquestions;
    }
    
    public void setVideoquestions(Set<Videoquestion> videoquestions) {
        this.videoquestions = videoquestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Normalquestion> getNormalquestions() {
        return this.normalquestions;
    }
    
    public void setNormalquestions(Set<Normalquestion> normalquestions) {
        this.normalquestions = normalquestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Score> getScores() {
        return this.scores;
    }
    
    public void setScores(Set<Score> scores) {
        this.scores = scores;
    }




}


