package com.cbtuser.entity;
// Generated Nov 2, 2019 11:33:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subtest generated by hbm2java
 */
@Entity
@Table(name="subtest"
    ,catalog="computerbasedtest"
)
public class Subtest  implements java.io.Serializable {


     private String id;
     private Test test;
     private String name;
     private int amount;
     private Set<Imagequestion> imagequestions = new HashSet<Imagequestion>(0);
     private Set<Audioquestion> audioquestions = new HashSet<Audioquestion>(0);
     private Set<Videoquestion> videoquestions = new HashSet<Videoquestion>(0);
     private Set<Normalquestion> normalquestions = new HashSet<Normalquestion>(0);
     private Set<Score> scores = new HashSet<Score>(0);

    public Subtest() {
    }

	
    public Subtest(String id, Test test, String name, int amount) {
        this.id = id;
        this.test = test;
        this.name = name;
        this.amount = amount;
    }
    public Subtest(String id, Test test, String name, int amount, Set<Imagequestion> imagequestions, Set<Audioquestion> audioquestions, Set<Videoquestion> videoquestions, Set<Normalquestion> normalquestions, Set<Score> scores) {
       this.id = id;
       this.test = test;
       this.name = name;
       this.amount = amount;
       this.imagequestions = imagequestions;
       this.audioquestions = audioquestions;
       this.videoquestions = videoquestions;
       this.normalquestions = normalquestions;
       this.scores = scores;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Test_id", nullable=false)
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Imagequestion> getImagequestions() {
        return this.imagequestions;
    }
    
    public void setImagequestions(Set<Imagequestion> imagequestions) {
        this.imagequestions = imagequestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Audioquestion> getAudioquestions() {
        return this.audioquestions;
    }
    
    public void setAudioquestions(Set<Audioquestion> audioquestions) {
        this.audioquestions = audioquestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Videoquestion> getVideoquestions() {
        return this.videoquestions;
    }
    
    public void setVideoquestions(Set<Videoquestion> videoquestions) {
        this.videoquestions = videoquestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Normalquestion> getNormalquestions() {
        return this.normalquestions;
    }
    
    public void setNormalquestions(Set<Normalquestion> normalquestions) {
        this.normalquestions = normalquestions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subtest")
    public Set<Score> getScores() {
        return this.scores;
    }
    
    public void setScores(Set<Score> scores) {
        this.scores = scores;
    }




}


