package com.cbtuser.entity;
// Generated Nov 8, 2019 8:58:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testmaker generated by hbm2java
 */
@Entity
@Table(name="testmaker"
    ,catalog="computerbasedtest"
)
public class Testmaker  implements java.io.Serializable {


     private String id;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String phoneNumber;
     private String email;
     private Set<Test> tests = new HashSet<Test>(0);
     private Set<Testmakerlog> testmakerlogs = new HashSet<Testmakerlog>(0);

    public Testmaker() {
    }

	
    public Testmaker(String id, String username, String password, String firstName) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.firstName = firstName;
    }
    public Testmaker(String id, String username, String password, String firstName, String lastName, String phoneNumber, String email, Set<Test> tests, Set<Testmakerlog> testmakerlogs) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.tests = tests;
       this.testmakerlogs = testmakerlogs;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=6)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=30)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="first_name", nullable=false, length=75)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=75)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone_number", length=13)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testmaker")
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testmaker")
    public Set<Testmakerlog> getTestmakerlogs() {
        return this.testmakerlogs;
    }
    
    public void setTestmakerlogs(Set<Testmakerlog> testmakerlogs) {
        this.testmakerlogs = testmakerlogs;
    }




}


