package com.cbtuser.entity;
// Generated Nov 17, 2019 4:32:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="computerbasedtest"
)
public class User  implements java.io.Serializable {


     private String id;
     private Institute institute;
     private Role role;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String phoneNumber;
     private String email;
     private Set<Userlog> userlogs = new HashSet<Userlog>(0);
     private Set<Test> tests = new HashSet<Test>(0);
     private Set<Coursedatabase> coursedatabases = new HashSet<Coursedatabase>(0);
     private Set<Question> questions = new HashSet<Question>(0);
     private Set<Score> scores = new HashSet<Score>(0);

    public User() {
    }

	
    public User(String id, Institute institute, Role role, String username, String password, String firstName, String phoneNumber, String email) {
        this.id = id;
        this.institute = institute;
        this.role = role;
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.phoneNumber = phoneNumber;
        this.email = email;
    }
    public User(String id, Institute institute, Role role, String username, String password, String firstName, String lastName, String phoneNumber, String email, Set<Userlog> userlogs, Set<Test> tests, Set<Coursedatabase> coursedatabases, Set<Question> questions, Set<Score> scores) {
       this.id = id;
       this.institute = institute;
       this.role = role;
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.userlogs = userlogs;
       this.tests = tests;
       this.coursedatabases = coursedatabases;
       this.questions = questions;
       this.scores = scores;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=9)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Institute_id", nullable=false)
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Role_id", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="username", nullable=false, length=30)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="first_name", nullable=false, length=75)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=75)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone_number", nullable=false, length=13)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Userlog> getUserlogs() {
        return this.userlogs;
    }
    
    public void setUserlogs(Set<Userlog> userlogs) {
        this.userlogs = userlogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Coursedatabase> getCoursedatabases() {
        return this.coursedatabases;
    }
    
    public void setCoursedatabases(Set<Coursedatabase> coursedatabases) {
        this.coursedatabases = coursedatabases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Score> getScores() {
        return this.scores;
    }
    
    public void setScores(Set<Score> scores) {
        this.scores = scores;
    }




}


