package com.cbtuser.entity;
// Generated Oct 19, 2019 10:48:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VidansquestionId generated by hbm2java
 */
@Embeddable
public class VidansquestionId  implements java.io.Serializable {


     private int id;
     private int videoQuestionId;
     private String videoQuestionQuestionDbId;
     private String videoQuestionSubTestId;

    public VidansquestionId() {
    }

    public VidansquestionId(int id, int videoQuestionId, String videoQuestionQuestionDbId, String videoQuestionSubTestId) {
       this.id = id;
       this.videoQuestionId = videoQuestionId;
       this.videoQuestionQuestionDbId = videoQuestionQuestionDbId;
       this.videoQuestionSubTestId = videoQuestionSubTestId;
    }
   


    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="VideoQuestion_id", nullable=false)
    public int getVideoQuestionId() {
        return this.videoQuestionId;
    }
    
    public void setVideoQuestionId(int videoQuestionId) {
        this.videoQuestionId = videoQuestionId;
    }


    @Column(name="VideoQuestion_QuestionDB_id", nullable=false, length=10)
    public String getVideoQuestionQuestionDbId() {
        return this.videoQuestionQuestionDbId;
    }
    
    public void setVideoQuestionQuestionDbId(String videoQuestionQuestionDbId) {
        this.videoQuestionQuestionDbId = videoQuestionQuestionDbId;
    }


    @Column(name="VideoQuestion_SubTest_id", nullable=false, length=10)
    public String getVideoQuestionSubTestId() {
        return this.videoQuestionSubTestId;
    }
    
    public void setVideoQuestionSubTestId(String videoQuestionSubTestId) {
        this.videoQuestionSubTestId = videoQuestionSubTestId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VidansquestionId) ) return false;
		 VidansquestionId castOther = ( VidansquestionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getVideoQuestionId()==castOther.getVideoQuestionId())
 && ( (this.getVideoQuestionQuestionDbId()==castOther.getVideoQuestionQuestionDbId()) || ( this.getVideoQuestionQuestionDbId()!=null && castOther.getVideoQuestionQuestionDbId()!=null && this.getVideoQuestionQuestionDbId().equals(castOther.getVideoQuestionQuestionDbId()) ) )
 && ( (this.getVideoQuestionSubTestId()==castOther.getVideoQuestionSubTestId()) || ( this.getVideoQuestionSubTestId()!=null && castOther.getVideoQuestionSubTestId()!=null && this.getVideoQuestionSubTestId().equals(castOther.getVideoQuestionSubTestId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getVideoQuestionId();
         result = 37 * result + ( getVideoQuestionQuestionDbId() == null ? 0 : this.getVideoQuestionQuestionDbId().hashCode() );
         result = 37 * result + ( getVideoQuestionSubTestId() == null ? 0 : this.getVideoQuestionSubTestId().hashCode() );
         return result;
   }   


}


