package com.cbtuser.entity;
// Generated Oct 19, 2019 10:48:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Videoquestion generated by hbm2java
 */
@Entity
@Table(name="videoquestion"
    ,catalog="computerbasedtest"
)
public class Videoquestion  implements java.io.Serializable {


     private VideoquestionId id;
     private Questiondb questiondb;
     private Subtest subtest;
     private String video;
     private String content;
     private String trueAnswer;
     private Set<Vidansquestion> vidansquestions = new HashSet<Vidansquestion>(0);

    public Videoquestion() {
    }

	
    public Videoquestion(VideoquestionId id, Questiondb questiondb, Subtest subtest, String video, String content, String trueAnswer) {
        this.id = id;
        this.questiondb = questiondb;
        this.subtest = subtest;
        this.video = video;
        this.content = content;
        this.trueAnswer = trueAnswer;
    }
    public Videoquestion(VideoquestionId id, Questiondb questiondb, Subtest subtest, String video, String content, String trueAnswer, Set<Vidansquestion> vidansquestions) {
       this.id = id;
       this.questiondb = questiondb;
       this.subtest = subtest;
       this.video = video;
       this.content = content;
       this.trueAnswer = trueAnswer;
       this.vidansquestions = vidansquestions;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="questionDbId", column=@Column(name="QuestionDB_id", nullable=false, length=10) ), 
        @AttributeOverride(name="subTestId", column=@Column(name="SubTest_id", nullable=false, length=10) ) } )
    public VideoquestionId getId() {
        return this.id;
    }
    
    public void setId(VideoquestionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QuestionDB_id", nullable=false, insertable=false, updatable=false)
    public Questiondb getQuestiondb() {
        return this.questiondb;
    }
    
    public void setQuestiondb(Questiondb questiondb) {
        this.questiondb = questiondb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SubTest_id", nullable=false, insertable=false, updatable=false)
    public Subtest getSubtest() {
        return this.subtest;
    }
    
    public void setSubtest(Subtest subtest) {
        this.subtest = subtest;
    }

    
    @Column(name="video", nullable=false)
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }

    
    @Column(name="content", nullable=false, length=500)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="true_answer", nullable=false, length=500)
    public String getTrueAnswer() {
        return this.trueAnswer;
    }
    
    public void setTrueAnswer(String trueAnswer) {
        this.trueAnswer = trueAnswer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="videoquestion")
    public Set<Vidansquestion> getVidansquestions() {
        return this.vidansquestions;
    }
    
    public void setVidansquestions(Set<Vidansquestion> vidansquestions) {
        this.vidansquestions = vidansquestions;
    }




}


