package com.cbt.entity;
// Generated Jan 18, 2020 5:56:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursedatabase generated by hbm2java
 */
@Entity
@Table(name="coursedatabase"
    ,catalog="computerbasedtest"
)
public class Coursedatabase  implements java.io.Serializable {


     private String id;
     private String name;
     private byte enableShuffle;
     private Set<Question> questions = new HashSet<Question>(0);
     private Set<Subtest> subtests = new HashSet<Subtest>(0);
     private Set<Expertise> expertises = new HashSet<Expertise>(0);

    public Coursedatabase() {
    }

	
    public Coursedatabase(String id, String name, byte enableShuffle) {
        this.id = id;
        this.name = name;
        this.enableShuffle = enableShuffle;
    }
    public Coursedatabase(String id, String name, byte enableShuffle, Set<Question> questions, Set<Subtest> subtests, Set<Expertise> expertises) {
       this.id = id;
       this.name = name;
       this.enableShuffle = enableShuffle;
       this.questions = questions;
       this.subtests = subtests;
       this.expertises = expertises;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=9)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="enable_shuffle", nullable=false)
    public byte getEnableShuffle() {
        return this.enableShuffle;
    }
    
    public void setEnableShuffle(byte enableShuffle) {
        this.enableShuffle = enableShuffle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coursedatabase")
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coursedatabase")
    public Set<Subtest> getSubtests() {
        return this.subtests;
    }
    
    public void setSubtests(Set<Subtest> subtests) {
        this.subtests = subtests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coursedatabase")
    public Set<Expertise> getExpertises() {
        return this.expertises;
    }
    
    public void setExpertises(Set<Expertise> expertises) {
        this.expertises = expertises;
    }




}


