package com.cbt.entity;
// Generated Jan 18, 2020 5:56:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Expertise generated by hbm2java
 */
@Entity
@Table(name="expertise"
    ,catalog="computerbasedtest"
)
public class Expertise  implements java.io.Serializable {


     private Integer id;
     private Coursedatabase coursedatabase;
     private User user;

    public Expertise() {
    }

    public Expertise(Coursedatabase coursedatabase, User user) {
       this.coursedatabase = coursedatabase;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CourseDatabase_id", nullable=false)
    public Coursedatabase getCoursedatabase() {
        return this.coursedatabase;
    }
    
    public void setCoursedatabase(Coursedatabase coursedatabase) {
        this.coursedatabase = coursedatabase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


